language: node_js
node_js:
  - '4.2'
before_install:
  - 'npm config set registry http://registry.npmjs.org'
install:
  - 'npm install'
script:
  - 'npm run lint'
  - 'npm run coverage'
notifications:
  webhooks: http://cloud-solutions-travis.mybluemix.net/notifications
