language: node_js
node_js:
  - '4.2'
install:
  - 'npm install'
before_script:
  - 'npm config set registry http://registry.npmjs.org'
script:
  - 'npm run lint'
  - 'npm run coverage'
notifications:
  webhooks: http://cloud-solutions-travis.mybluemix.net/notifications
